// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dapTest.Data;

#nullable disable

namespace dapTest.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221026115501_Createinitial")]
    partial class Createinitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("dapTest.Gruppe11", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("etternavn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("navn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("dbGruppe");
                });
#pragma warning restore 612, 618
        }
    }
}
